### PR TITLE
Initial thread support & shutdown hook.

### PR DESCRIPTION
**Pull request by n1zea144**
Very preliminary thoughts on subscriptions.

### CODE REVIEW

**Review by ao508 — COMMENTED** [review]
I think you need to update your pom with this 

```
    <dependency>
      <groupId>com.github.mskcc</groupId>
      <artifactId>cmo-messaging-java</artifactId>
      <version>b88a0cdd435c79a8aab7c4ffe480472de5bac4a6</version>
    </dependency>
```

**Comment by n1zea144** [comment]
There were a few poms I needed to update to get this to run locally (service & persistence as well as the root pom).  I didn't check in any of those other changes because I thought you would do that once you were ready to integrate the other depedencies.  In any event, I made the update to the root pom as you requested.

**Comment by ao508** [comment]
Ah for the pom update I added properties so now it looks like this


```
    <dependency>
      <groupId>${messaging.java.groupId}</groupId>
      <artifactId>${messaging.java.artifactId}</artifactId>
      <version>${messaging.java.version}</version>
    </dependency>
```

and the properties are this

```
    <messaging.java.groupId>com.github.mskcc</messaging.java.groupId>
    <messaging.java.artifactId>cmo-messaging-java</messaging.java.artifactId>
    <messaging.java.version>v1.0-alpha</messaging.java.version>
```

I think just one is missing from the changes in this pr?

**Comment by ao508** [comment]
@n1zea144 the changes i made to your branch are here https://github.com/n1zea144/cmo-metadb/pull/1/files

**Review by ao508 — APPROVED** [review]

**Pull request merged**
